### PR TITLE
rhel7: Install openssl11-libs

### PR DESCRIPTION
**Pull request by mamedin**
Connects to #23

### CODE REVIEW

**Comment by mamedin** [comment]
I know it is an horrible fix, but probably EPEL repo is not going to be updated anymore for RHEL7.

Other option is to left open the issue and skip this PR. Probably we are not going to install so many RHEL7.

**Review by currmie — APPROVED** [review]
LGTM

**Review by DavidHume-ArtefactualSystems — APPROVED** [review]
Yep, even if there's still a RHEL7 method out there installing the library via EPEL, this should work either way to assure it is installed, if'n I be reading it right.

**Comment by mamedin** [comment]
PR merged

**Pull request merged**
